version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-yaml
    volumes:
      - uwsgi_data:/tmp/uwsgi/:ro
      - web_static:/app/static/:ro
      - web_media:/app/media/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - foodie_network
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodie-yaml
    env_file:
      - .env
    volumes:
      - data:/app/sql/
      - uwsgi_data:/tmp/uwsgi/
    networks:
      - foodie_network

volumes:
  data:
  uwsgi_data:
  web_static:
  web_media:

networks:
   foodie_network:
        driver: bridge
