version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-yaml
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/app/static/:ro
      - web_media:/app/media/:ro
    ports:
      - "8000:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodie-yaml
    env_file:
      - .env
    volumes:
      - data:/app/sql
    ports:
      - "8747:8000"

volumes:
  data:
  uwsgi_data:
  web_static:
  web_media: