version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-yaml
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/foodie_be/static/:ro
      - web_media:/foodie_be/media/
      - cert:/foodie_be/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - foodie_network
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodie-yaml
    env_file:
      - .env
    restart: always
    command: >
      sh -c "uwsgi --ini uwsgi.ini"
    volumes:
      - data:/foodie_be/sql/
      - cert:/foodie_be/nginx/ssl/
      - uwsgi_data:/tmp/uwsgi/
      - web_media:/foodie_be/media/
      - web_static:/foodie_be/static/
    networks:
      - foodie_network

volumes:
  data:
  cert:
  uwsgi_data:
  web_static:
  web_media:

networks:
   foodie_network:
        driver: bridge
